language: android
android: 
    components: 
    - tools
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
branches:
  only:
  - develop
deploy: 
  provider: releases
  api_key: ${Travis_GH_TOKEN}
  file: "app/build/outputs/apk/app-debug.apk"
  skip_cleanup: true
  on: 
    all_branches: true

notifications: 
  slack: perrinn:QiSIQnmPR2DQJGwbUjjp7m7D

  
