language: android

android: 
    components: 
    - tools
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
branches:
  except:
  - experimental
  - main

branches:
  only:
  - Ambitious_Artichoke_CM_Deploy_Attempt_2
  
deploy: 
  provider: releases
  api_key: ${Travis_GH_TOKEN}
  file: "app/build/outputs/apk/app-debug.apk"
  skip_cleanup: true
  on: 
    branch: Ambitious_Artichoke_CM_Deploy_Attempt_2

notifications: 
  slack: perrinn:QiSIQnmPR2DQJGwbUjjp7m7D

  
