language: android
android: 
    components: 
    - tools
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
deploy: 
  api_key: "${Travis_GH_TOKEN}"
  file: app/build/outputs/apk/app-debug.apk
  provider: release
  skip_cleanup: true
  on: 
    all_branches: true
language: android
notifications: 
  slack: perrinn:QiSIQnmPR2DQJGwbUjjp7m7D

  
